[build]
  command = "npm run test:ci && npm run build"
  publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

# 🔥🛡️ SECURITY HEADERS CONFIGURATION 🛡️🔥
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy - Prevents XSS attacks
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://fonts.googleapis.com https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https: blob:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://cdn.contentful.com https://images.ctfassets.net https://api.openai.com; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"
    
    # Clickjacking protection
    X-Frame-Options = "DENY"
    
    # MIME type sniffing protection
    X-Content-Type-Options = "nosniff"
    
    # XSS protection for legacy browsers
    X-XSS-Protection = "1; mode=block"
    
    # Referrer policy for privacy
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Permissions policy to restrict dangerous features
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()"
    
    # Strict Transport Security (already present but ensuring consistency)
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"


